### ISSUE TITLE
Compatible with drive-db

### ISSUE THREAD

**Issue by franciscop** [leftlogic/file-db#1]
Hi, I'm the creator of [drive-db](https://github.com/franciscop/drive-db). I love what I've seen so far of file-db, and I think it's really similar in scope to my library. So I propose to make them compatible:
- Allow for a default table in your code. So people can do `db.find()` instead of requiring `db.use('db').find()`. It would use `db` file by default and it would be backward-compatible.
- Change both names for connecting. Instead of drive's `load`, or file's `open`, I propose to use `connect` in a similar fashion to mongoose.
- Add the find queries from drive to file, which are also similar to mongodb

I could implement 1. and 2. and maybe 3. if the changes are welcome and make a pull request. In this way they would be compatible and just changing a couple of things you can swap database engines easily.

Note: drive-db cannot `save` documents since that would need write permissions from google drive, including keys and other really burdersome configurations that I thought wasn't worth it for the end user.

**Comment by tgvashworth** [comment]
Hey @franciscop! This would be really, really cool. Unfortunately, this project isn't maintained (and I'm not even sure it's actually used any more) so it might not be the most valuable use of your time. That said, if you'd like to do it then absolutely go ahead!

**Comment by remy** [comment]
What @phuu said (though I had no idea that you would be even watching this repo! Ta).

**Comment by tgvashworth** [comment]
@remy I have eyes everywhere

**Comment by franciscop** [comment]
I see, actually a friend of mine pointed to a big issue I didn't know when I showed him this repo: that the file systems in some node hostings (as heroku) is _ephemeral_; it gets destroyed with each deploy, so a file system db is not as useful as I thought. If I change my hosting or really feel like implementing it I'd try to do this, otherwise I'll follow your advice. Sorry for bothering you guys.
